### ISSUE TITLE
Regarding using index as stocks

### ISSUE THREAD

**Issue by mandarpriya** [fmilthaler/FinQuant#34]
Hi Sir,
I have just started with Python and  cam across the FinQuant documentation. Was successful in replicating the code for stocks, but when i am trying to use S&P, FTSE and Nikkei in place of stocks then i receive an error. So could help me with the issue.

**Comment by fmilthaler** [comment]
Hi, and apologies for the late response. 

I presume you are doing something like this:
```
# ticker names:
names = ["S&P", "FSTE", "Nikkei"]
# build portfolio:
pf = build_portfolio(names=names)
```

**Note**: FinQuant uses two different sources to get stock data from:
1. Quandl (this is the default)
2. Yahoo Finance

Each source might have different ticker names for the indices you are looking to obtain. If you are unsure what the correct ticker is, I'd suggest you check [Yahoo Finance](https://finance.yahoo.com/) and search for the [S&P 500](https://finance.yahoo.com/quote/%5EGSPC?p=^GSPC&.tsrc=fin-srch). On that page you can see what the correct ticker for S&P 500 is: **^GSPC**.

To answer your question, try the following:
```
names = ["^GSPC", "^FTSE", "^N225"]
pf = build_portfolio(names=names, data_api="yfinance")
```
This will download data for *S&P 500*, *FTSE*, *Nikkei* respectively.

Let me know if that solves your problem.

**Comment by fmilthaler** [comment]
While testing this, I noticed that FinQuant should result in a better error message, if one of the stocks could not be downloaded from Quandl (Yahoo Finance/yfinance gives an appropriate error message that is passed on to the user).

**Comment by mandarpriya** [comment]
Sir,
Thanks for reply,
However the error obtained r 
after following 
from finquant.portfolio import build_portfolio
names = ["^GSPC","^FTSE","^N225"]
pf = build_portfolio(names=names, data_api="yfinance")


IndexError                                Traceback (most recent call last)
<ipython-input-9-c4e45dd2f6d9> in <module>
      2 names = ["^GSPC","^FTSE","^N225"]
      3 
----> 4 pf = build_portfolio(names=names, data_api="yfinance")

~\Anaconda3\lib\site-packages\finquant\portfolio.py in build_portfolio(**kwargs)
   1151             )
   1152         # get portfolio:
-> 1153         pf = _build_portfolio_from_api(**kwargs)
   1154 
   1155     # 2. pf_allocation, data

~\Anaconda3\lib\site-packages\finquant\portfolio.py in _build_portfolio_from_api(names, pf_allocation, start_date, end_date, data_api)
    933         pf_allocation = _generate_pf_allocation(names=names)
    934     # build portfolio:
--> 935     pf = _build_portfolio_from_df(data, pf_allocation)
    936     return pf
    937 

~\Anaconda3\lib\site-packages\finquant\portfolio.py in _build_portfolio_from_df(data, pf_allocation, datacolumns)
   1045             stock_data.name = datacolumns[0]
   1046         # create Stock instance and add it to portfolio
-> 1047         pf.add_stock(Stock(pf_allocation.loc[i], data=stock_data))
   1048     return pf
   1049 

~\Anaconda3\lib\site-packages\finquant\portfolio.py in __init__(self, investmentinfo, data)
     98         self.expected_return = self.comp_expected_return()
     99         self.volatility = self.comp_volatility()
--> 100         self.skew = self._comp_skew()
    101         self.kurtosis = self._comp_kurtosis()
    102 

~\Anaconda3\lib\site-packages\finquant\portfolio.py in _comp_skew(self)
    134     def _comp_skew(self):
    135         """Computes and returns the skewness of the stock."""
--> 136         return self.data.skew().values[0]
    137 
    138     def _comp_kurtosis(self):

IndexError: index 0 is out of bounds for axis 0 with size 0
so do let me know what could be the possible mistake i am commit

**Comment by drcsturm** [comment]
Quandl requires a paid subscription to download ETF data. Check that you have your api key for a paid subscription. Otherwise use yfinance.

**Comment by fmilthaler** [comment]
Thank you both for contributing to the project by reporting this and providing more insights. 

I've been gone for a long time and just recently returned to this project. 

I just tried to replicate this issue, but was unable to. The source code as well as dependencies have changed quite a bit in the past few weeks, which could be why I don't see this error.

Hence I'm closing this issue now.
