### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (5,) (4,) 

### ISSUE THREAD

**Issue by mbatzeris** [fmilthaler/FinQuant#38]
Hi, I'm getting the following error when the number of tickers  is more than 5 
![FINQUANT](https://user-images.githubusercontent.com/46544375/70561059-74625d00-1b92-11ea-8e06-7bd8304272ef.png)

**Comment by fmilthaler** [comment]
Hi there, the error you are getting is due to having missed a `,` between `"MSFT"` and `"BIP"`.
I tested it with the `,`, and it works fine.
