### ISSUE TITLE
AttributeError: module 'pandas.core' has no attribute 'index'

### ISSUE THREAD

**Issue by slpenn13** [fmilthaler/FinQuant#39]
Causes: tests to fail with pandas (panda.core now PRIVATE).

**Comment by slpenn13** [comment]
After replacing pd.MultiIndex causes:
(1) all 59 tests to pass
(2) portfolio example to run

**Comment by LevPerla** [comment]
To fix that you need to replace in portfolio.py all cases of 
pd.core.index.MultiIndex 
with
pd.core.indexes.multi.MultiIndex

**Comment by slpenn13** [comment]
Completed Feb 12 -- see my branch, thank you!!

Stephen L. Pennington
C: (646) 640-6602
G: Austin, TX
E:    slpenn13@hotmail.com


________________________________

**Comment by fmilthaler** [comment]
This has been solved by merge #46
