### ISSUE TITLE
Error on data download

### ISSUE THREAD

**Issue by sweetatyagiaz** [fmilthaler/FinQuant#63]
getting error when i run the commend 
pf = build_portfolio(names=['GOOG', 'AMZN'],
                    start_date=start_date,
                    end_date=end_date)

**Exception**: Error during download of stock data from Quandl.
Make sure all the requested stock names/tickers are supported by Quandl.

Kindly solve the issue

**Comment by fmilthaler** [comment]
Hi there. 

You could try the following:
```
import quandl
stock_data = quandl.get(['GOOG', 'AMZN'], start_date=start_date, end_date=end_date)
```
And check if that was successful. 

Also, you could try downloading the data from Yahoo Finance instead. Try:
```
pf = build_portfolio(names=['GOOG', 'AMZN'], start_date=start_date, end_date=end_date, data_api="yfinance")
```

I hope this helps.

**Comment by sweetatyagiaz** [comment]
Thanks for the reply. yahoo finance api is working.
