### ISSUE TITLE
Depreciation pandas

### ISSUE THREAD

**Issue by Leohanhart** [fmilthaler/FinQuant#73]
Error while using package
# error
-packages\finquant\portfolio.py:260: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self.portfolio = self.portfolio.append(stock.investmentinfo, ignore_index=True)

Cant this problem be solved.

**Comment by onenetbee** [comment]
I also get this problem for "AttributeError: 'DataFrame' object has no attribute 'append'"
I change to concat but it doesn't work

**Comment by fmilthaler** [comment]
@Leohanhart  and @onenetbee, thank you two for reporting this, and my dearest apologies for this taking so long. I have been absent from GitHub for a long time, but thanks to @PietropaoloFrisoni, this is finally fixed. More issues are worked on now.

**Comment by onenetbee** [comment]
@fmilthaler Thank you very much!

**Comment by onenetbee** [comment]
@PietropaoloFrisoni Thank you very much! I just read the reply and I will try with your method.

**Comment by fmilthaler** [comment]
@onenetbee I'll also create and upload a new version of FinQuant in the next few days, when other things have been fixed. So if you are still interested, look out for that.

**Comment by onenetbee** [comment]
OK, Thank you.

Dans

Frank Milthaler ***@***.***> 于2023年7月7日周五 12:55写道：
