### ISSUE TITLE
Use type hints consistently

### ISSUE THREAD

**Issue by fmilthaler** [fmilthaler/FinQuant#94]
As part of that: where a variable could be either `pd.Series` or `pd.DataFrame`, do sth like the following:

```
DataFrameOrSeries = Union[pd.DataFrame, pd.Series]

def compute_ma(
    data: DataFrameOrSeries, fun: Callable, spans: List[int], plot: bool = True
) -> pd.DataFrame:
    # rest of function
```

While at it, fix pylint issues as well.

**Comment by fmilthaler** [comment]
@PietropaoloFrisoni , I'm already working on this (been doing that for the past few days offline, just pushed the branch for visibility: #122). In that PR I'm also addressing the other issue #95 (pylint and mypy errors).

**Comment by PietropaoloFrisoni** [comment]
Good, thanks. Good luck!

**Comment by fmilthaler** [comment]
> Good, thanks. Good luck!

If you look at the current state of the [PR](https://github.com/fmilthaler/FinQuant/pull/122) I bet you're happy that I ended up taking this on ;)
