### ISSUE TITLE
Detect and fix issues with mypy and pylint

### ISSUE THREAD

**Issue by fmilthaler** [fmilthaler/FinQuant#95]
Run both mypy and pylint on the code base and (slowly) fix issues

**Comment by fmilthaler** [comment]
Example: 
For issues with matplotlib.pyplot, do:
```
import matplotlib.pyplot as plt  # type: ignore
```

**Comment by pythonhacker** [comment]
I will be happy to look at this if you are fine with it. Also perhaps kindly look at issue #119

**Comment by fmilthaler** [comment]
@pythonhacker Thanks, but I'm already working on this one these days. PR #122 should be ready in the next few days.

**Comment by fmilthaler** [comment]
Actually, this is a sort of duplicate of #94. Closing this now.
